## PART - 1
#### TASK - 1

dataset : https://www.kaggle.com/datasets/karkavelrajaj/amazon-sales-dataset

In [222]:
# Import required library
import pandas as pd

In [223]:
# Load the dataset from CSV file
# Make sure "Reviews.csv" is in the same folder as your notebook

df = pd.read_csv("amazon.csv")

In [224]:
# Print number of rows and columns in dataset
df.shape

(1465, 16)

In [225]:
# Display all column names in dataset
df.columns

Index(['product_id', 'product_name', 'category', 'discounted_price',
       'actual_price', 'discount_percentage', 'rating', 'rating_count',
       'about_product', 'user_id', 'user_name', 'review_id', 'review_title',
       'review_content', 'img_link', 'product_link'],
      dtype='str')

In [226]:
# Show first 5 records to understand structure
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

In [227]:
df.describe()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link
count,1465,1465,1465,1465,1465,1465,1465,1463,1465,1465,1465,1465,1465,1465,1465,1465
unique,1351,1337,211,550,449,92,28,1143,1293,1194,1194,1194,1194,1212,1412,1465
top,B07JW9H4J1,"Fire-Boltt Ninja Call Pro Plus 1.83"" Smart Wat...",Computers&Accessories|Accessories&Peripherals|...,₹199,₹999,50%,4.1,"9,378",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...","I am not big on camera usage, personally. I wa...",https://m.media-amazon.com/images/I/413sCRKobN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
freq,3,5,233,53,120,56,244,9,6,10,10,10,10,8,3,1

In [228]:
# Count missing values in each column
df.isnull().sum()

product_id             0
product_name           0
category               0
discounted_price       0
actual_price           0
discount_percentage    0
rating                 0
rating_count           2
about_product          0
user_id                0
user_name              0
review_id              0
review_title           0
review_content         0
img_link               0
product_link           0
dtype: int64

In [229]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1465 entries, 0 to 1464
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1465 non-null   str
 1   product_name         1465 non-null   str
 2   category             1465 non-null   str
 3   discounted_price     1465 non-null   str
 4   actual_price         1465 non-null   str
 5   discount_percentage  1465 non-null   str
 6   rating               1465 non-null   str
 7   rating_count         1463 non-null   str
 8   about_product        1465 non-null   str
 9   user_id              1465 non-null   str
 10  user_name            1465 non-null   str
 11  review_id            1465 non-null   str
 12  review_title         1465 non-null   str
 13  review_content       1465 non-null   str
 14  img_link             1465 non-null   str
 15  product_link         1465 non-null   str
dtypes: str(16)
memory usage: 4.7 MB

#### TASK - 2

In [230]:
# Import required libraries for text preprocessing
import re
import string
import pandas as pd

# NLTK for stopwords removal
import nltk
from nltk.corpus import stopwords

# Download stopwords (run once)
nltk.download('stopwords')

# Load English stopwords set
stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [231]:
def clean_text(text):
    
    # 1. Convert text to lowercase
    text = text.lower()
    
    # 2. Remove punctuation and special characters
    text = re.sub(r'[^a-z\s]', '', text)
    
    # 3. Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    # 4. Remove stopwords
    words = text.split()
    words = [word for word in words if word not in stop_words]
    
    return " ".join(words)

In [232]:
df["text"] = (
    df["product_name"].astype(str) + " " +
    df["category"].astype(str) + " " +
    df["about_product"].astype(str)
)

In [233]:
# Apply preprocessing to all rows in combined_text column

df["clean_text"] = df['review_content'].apply(clean_text)

In [234]:
df.head()

,product_id,product_name,category,discounted_price,actual_price,discount_percentage,rating,rating_count,about_product,user_id,user_name,review_id,review_title,review_content,img_link,product_link,text,clean_text
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories|Accessories&Peripherals|...,₹399,"₹1,099",64%,4.2,"24,269",High Compatibility : Compatible With iPhone 12...,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...,Wayona Nylon Braided USB to Lightning Fast Cha...,looks durable charging fine toono complainscha...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories|Accessories&Peripherals|...,₹199,₹349,43%,4.0,"43,994","Compatible with all Type C enabled devices, be...","AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,ordered cable connect phone android auto car c...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories|Accessories&Peripherals|...,₹199,"₹1,899",90%,3.9,"7,928",【 Fast Charger& Data Sync】-With built-in safet...,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...,Sounce Fast Phone Charging Cable & Data Sync U...,quite durable sturdyhttpsmmediaamazoncomimages...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories|Accessories&Peripherals|...,₹329,₹699,53%,4.2,"94,363",The boAt Deuce USB 300 2 in 1 cable is compati...,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,good productlong wirecharges goodnicei bought ...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories|Accessories&Peripherals|...,₹154,₹399,61%,4.2,"16,905",[CHARGE & SYNC FUNCTION]- This cable comes wit...,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,bought instead original apple work rs fast app...

## PART - 2
#### TASK - 3

In [235]:
# Import TF-IDF vectorizer from sklearn
from sklearn.feature_extraction.text import TfidfVectorizer

In [236]:
# Create TF-IDF Vectorizer
# max_features limits vocabulary size (faster + avoids noise)
# ngram_range (1,2) captures single words + word pairs

tfidf = TfidfVectorizer(
    max_features=5000,   # keep top 5000 important words
    ngram_range=(1, 2)   # unigrams + bigrams
)

In [237]:
tfidf_matrix = vectorizer.fit_transform(df["text"])

In [238]:
# Display number of rows and features
print("TF-IDF Matrix Shape:", tfidf_matrix.shape)

TF-IDF Matrix Shape: (1465, 10361)

#### TASK - 4

In [239]:
# Cosine similarity is used to measure similarity between text vectors
from sklearn.metrics.pairwise import cosine_similarity

In [240]:
# Compute cosine similarity between all product vectors

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")

In [241]:
from sklearn.metrics.pairwise import cosine_similarity

similarity_matrix = cosine_similarity(tfidf_matrix)

In [242]:
# Store similarity matrix in dataframe format (optional)

similarity_df = pd.DataFrame(similarity_matrix)
similarity_df.head()

,0,1,2,3,4,5,6,7,8,9,...,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464
0,1.000000,0.150876,0.321536,0.134680,0.418666,0.184615,0.164898,0.089544,0.054500,0.162856,...,0.030752,0.021658,0.017476,0.027161,0.009979,0.001557,0.000000,0.027136,0.036101,0.002039
1,0.150876,1.000000,0.167355,0.251194,0.230049,0.369413,0.291715,0.311108,0.028976,0.782506,...,0.005973,0.004655,0.016041,0.019386,0.001311,0.008583,0.000000,0.000000,0.011518,0.021985
2,0.321536,0.167355,1.000000,0.130565,0.268511,0.216498,0.193073,0.149942,0.066497,0.173448,...,0.012140,0.019138,0.000000,0.028307,0.011123,0.016873,0.000000,0.019099,0.033010,0.000000
3,0.134680,0.251194,0.130565,1.000000,0.154621,0.281214,0.588620,0.268568,0.044105,0.323064,...,0.019057,0.009118,0.018356,0.013037,0.004065,0.001772,0.000000,0.012424,0.016786,0.017042
4,0.418666,0.230049,0.268511,0.154621,1.000000,0.284324,0.204116,0.206258,0.035038,0.248269,...,0.011458,0.065258,0.020350,0.016849,0.022890,0.011857,0.004379,0.015097,0.017924,0.025105

3. Explain briefly why cosine similarity is used.

    Cosine similarity measures the angle between two vectors.

    ✔ It ignores magnitude (length of text)
    ✔ Focuses only on meaning similarity
    ✔ Works very well for TF-IDF text data
    ✔ Commonly used in recommendation systems

    Formula idea:
    cos(θ) = (A · B) / (||A|| ||B||)

## PART - 3
#### TASK - 5

In [243]:
# -----------------------------
# Product Name Recommendation
# -----------------------------
def recommend(product_name, top_n=5):

    # fuzzy/partial match (important fix)
    matches = df[df["product_name"].str.contains(product_name, case=False, na=False)].index.tolist()

    if not matches:
        return "Product not found. Try a different name."

    idx = matches[0]

    # similarity scores
    sim_scores = list(enumerate(similarity_matrix[idx]))

    # sort by similarity (skip itself)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]

    recommended_idx = [i[0] for i in sim_scores]

    return df.loc[recommended_idx, ["product_name", "category", "rating"]]

In [244]:
# -----------------------------

# TEST

# -----------------------------

print(recommend("boAt", 5))

print(recommend("Redmi", 5))

print(recommend("Samsung", 5))

                                          product_name  \
392  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
628  boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
92   boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...
113  boAt Type C A750 Stress Resistant, Tangle-free...
74   boAt Type C A750 Stress Resistant, Tangle-free...

                                              category rating
392  Computers&Accessories|Accessories&Peripherals|...    4.2
628  Computers&Accessories|Accessories&Peripherals|...    4.2
92   Computers&Accessories|Accessories&Peripherals|...    4.2
113  Computers&Accessories|Accessories&Peripherals|...    4.1
74   Computers&Accessories|Accessories&Peripherals|...    4.1
                                          product_name  \
953  Redmi 80 cm (32 inches) Android 11 Series HD R...
278  Mi 100 cm (40 inches) Horizon Edition Full HD ...
41   Mi 108 cm (43 inches) Full HD Android LED TV 4...
16   MI 80 cm (32 inches) 5A Series HD Ready Smart ...
310  MI 80 cm (32 inches) HD Ready Smart Android LE...

                                              category rating
953  Electronics|HomeTheater,TV&Video|Televisions|S...    4.2
278  Electronics|HomeTheater,TV&Video|Televisions|S...    4.2
41   Electronics|HomeTheater,TV&Video|Televisions|S...    4.3
16   Electronics|HomeTheater,TV&Video|Televisions|S...    4.2
310  Electronics|HomeTheater,TV&Video|Televisions|S...    4.2
                                          product_name  \
723  Samsung 80 cm (32 Inches) Wondertainment Serie...
152  Samsung 80 cm (32 inches) Wondertainment Serie...
276  Samsung 138 cm (55 inches) Crystal 4K Series U...
61   Samsung 108 cm (43 inches) Crystal 4K Neo Seri...
192  Samsung 138 cm (55 inches) Crystal 4K Neo Seri...

                                              category rating
723  Electronics|HomeTheater,TV&Video|Televisions|S...    4.3
152  Electronics|HomeTheater,TV&Video|Televisions|S...    4.3
276  Electronics|HomeTheater,TV&Video|Televisions|S...    4.3
61   Electronics|HomeTheater,TV&Video|Televisions|S...    4.3
192  Electronics|HomeTheater,TV&Video|Televisions|S...    4.3

## PART - 4
#### TASK - 6

app.py file